"""
Proactive nudges (option B): twice-daily context-aware check-ins.

bhAI initiates a short voice message in the morning (~10am IST) and at
night (~9pm IST) for opted-in pilot users. The nudge is generated by the
same LLM with the user's full context (memory, profile, recent history)
plus a "nudge mode" instruction so it picks up where the last conversation
left off rather than launching into a sales pitch.

Safety rails:
- NUDGE_ENABLED master kill switch (default false)
- NUDGE_PHONES allow-list of phone hashes (empty = nobody gets nudged)
- One nudge per slot per day (tracked in `nudges` table)
- Quiet hours: never fire between 23:00 and 08:00 IST
- Skip if user just messaged (active conversation, don't interrupt)
- Skip if user has fewer than 1 message in the last `nudge_active_user_days`
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from datetime import time as dtime
from datetime import timedelta, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from src.bhai.config import DATA_DIR, KNOWLEDGE_BASE_DIR, Config
from src.bhai.llm import create_llm
from src.bhai.llm.base import _JSON_OUTPUT_INSTRUCTION, BaseLLM
from src.bhai.memory.store import ConversationStore

logger = logging.getLogger("bhai.nudges")

IST = timezone(timedelta(hours=5, minutes=30))

# Slots — extend here if we add more nudge times later
SLOT_MORNING = "morning"
SLOT_AFTERNOON = "afternoon"
SLOT_NIGHT = "night"

# Quiet hours: never nudge before this hour or after this hour, IST.
QUIET_BEFORE_HOUR = 8
QUIET_AFTER_HOUR = 23

# Don't nudge if the user has messaged in the last N hours — they're active or
# only just wrapped up, and a nudge would feel intrusive. 3h gives enough room
# that the conversation has actually settled before we check in.
SKIP_IF_USER_ACTIVE_HOURS = 3

# One nudge per slot per 18 hours (prevents double-fire if loop overlaps a window
# or the process restarts mid-window).
MIN_GAP_BETWEEN_SAME_SLOT_HOURS = 18


# ── Pure decision logic (testable without DB / network) ───────────────


def current_slot(
    now_ist: datetime,
    morning_hour: int,
    night_hour: int,
    window_minutes: int,
    afternoon_hour: Optional[int] = None,
) -> Optional[str]:
    """If `now_ist` falls inside a slot's firing window, return the slot name.

    Each slot has a window of `window_minutes` starting at the configured hour
    (e.g. morning_hour=10, window=30 → fires between 10:00 and 10:30 IST).
    The afternoon joke slot is opt-in (pass `afternoon_hour`). Outside any
    window, returns None.
    """
    if not (QUIET_BEFORE_HOUR <= now_ist.hour < QUIET_AFTER_HOUR):
        return None

    slot_starts = {
        SLOT_MORNING: dtime(hour=morning_hour),
        SLOT_NIGHT: dtime(hour=night_hour),
    }
    if afternoon_hour is not None:
        slot_starts[SLOT_AFTERNOON] = dtime(hour=afternoon_hour)
    now_t = now_ist.time()
    for slot, start in slot_starts.items():
        end_dt = (
            datetime.combine(now_ist.date(), start) + timedelta(minutes=window_minutes)
        ).time()
        if start <= now_t <= end_dt:
            return slot
    return None


def should_nudge_user(
    *,
    now_ist: datetime,
    slot: str,
    last_user_message_at: Optional[datetime],
    last_nudge_at: Optional[datetime],
    throttle_hours: Optional[int] = None,
    last_any_nudge_at: Optional[datetime] = None,
) -> bool:
    """Pure check: should we send a `slot` nudge to this user right now?

    - Skip if they messaged us in the last SKIP_IF_USER_ACTIVE_HOURS — don't
      interrupt an active conversation.
    - If `throttle_hours` is set: skip if ANY nudge fired within `throttle_hours`
      (covers users who explicitly asked for less frequent contact).
    - Otherwise: skip if we've already nudged this slot in the last
      MIN_GAP_BETWEEN_SAME_SLOT_HOURS — once a window per day.
    """
    if last_user_message_at is not None:
        if now_ist - last_user_message_at < timedelta(hours=SKIP_IF_USER_ACTIVE_HOURS):
            return False

    if throttle_hours is not None and throttle_hours > 0:
        # User has explicitly requested less frequent nudges. Treat any nudge
        # in either slot as the gating event.
        if last_any_nudge_at is not None:
            if now_ist - last_any_nudge_at < timedelta(hours=throttle_hours):
                return False
    else:
        if last_nudge_at is not None:
            if now_ist - last_nudge_at < timedelta(
                hours=MIN_GAP_BETWEEN_SAME_SLOT_HOURS
            ):
                return False

    # Slot name must be one we know about.
    return slot in (SLOT_MORNING, SLOT_AFTERNOON, SLOT_NIGHT)


WILDCARD_ALL = "*"


def parse_allowlist(raw: str) -> List[str]:
    """Comma/whitespace-separated phone-hash allowlist → cleaned list.

    Returns empty list for empty/blank input. The wildcard ``*`` is NOT
    treated as a hash here — callers should detect it explicitly via
    `is_wildcard_allowlist()` before consulting this list.
    """
    if not raw:
        return []
    return [p.strip() for p in raw.replace("\n", ",").split(",") if p.strip()]


def is_wildcard_allowlist(raw: str) -> bool:
    """True iff `NUDGE_PHONES` is set to the `*` sentinel (= every active user)."""
    return (raw or "").strip() == WILDCARD_ALL


def select_nudge_candidates(
    active_phones: List[str],
    nudge_phones_raw: str,
    phone_hash_fn: Callable[[str], str],
) -> List[str]:
    """Filter the active-users list down to those eligible for a nudge.

    - `NUDGE_PHONES=*` → every active user is a candidate (auto-includes new
      pilot users without an env var update).
    - `NUDGE_PHONES=hash1,hash2` → only the listed phone hashes.
    - `NUDGE_PHONES=` (empty) → nobody (defensive default).
    """
    if is_wildcard_allowlist(nudge_phones_raw):
        return list(active_phones)
    allowlist = set(parse_allowlist(nudge_phones_raw))
    if not allowlist:
        return []
    return [p for p in active_phones if phone_hash_fn(p) in allowlist]


# ── Prompt construction ──────────────────────────────────────────────


def _slot_time_hint(slot: str) -> str:
    """Human-readable time-of-day hint passed to the LLM."""
    if slot == SLOT_MORNING:
        return "सुबह (around 10am IST)"
    if slot == SLOT_NIGHT:
        return "रात (around 9pm IST)"
    return slot


NUDGE_INSTRUCTION = """\
=== Nudge Mode ===
You are starting a NEW message to the user — they did NOT message you. You're
reaching out first, like a sister who suddenly thought of them while folding
clothes or making chai.

This is a CHECK-IN, not a request, not a survey, not a reminder.

═══════════════════════════════════════════════════════════════════════════
RULE 1 (most important) — RESPECTFUL SPEECH. AAP-FORM ONLY.
═══════════════════════════════════════════════════════════════════════════

bhAI is addressing an artisan woman — likely older than itself, in a new
relationship with this technology. The single most important choice in the
opener is the second-person register. Default to AAP, never tum, never tu.

  ✅ "Sonal ji, namaste! आज का दिन कैसा रहा?"
  ✅ "Manimala ji, kaise hain aaj? Aaj loom kaisa chala?"
  ✅ "बताइएगा जब time मिले" / "Bataaiyega jab time mile"
  ✅ "कैसा है आज?" / "Kaisa hai aaj?" (ungendered impersonal verb — ok)

  ❌ "कैसी हो आज?" / "Kaisi ho?" (tum-form + feminine gendering — the v1.5 bug)
  ❌ "क्या कर रही हो?" / "Kya kar rahi ho?" (tum + feminine)
  ❌ "बता ना" / "बता तो" (tum imperative)
  ❌ Anything starting with "तू" or "tu" — never.

Same rule applies to Marathi/Gujarati/Bengali — use the formal-respectful
register. For Tamil/Telugu/Malayalam/Kannada, use the formal second-person.
If unsure, address by name with the -ji honorific + plural-verb constructions
that avoid pronouns entirely.

═══════════════════════════════════════════════════════════════════════════
RULE 2 — WARMTH FIRST. SUBSTANCE SECOND.
═══════════════════════════════════════════════════════════════════════════

THIS IS THE BIGGEST CHANGE FROM THE OLD PROMPT. The old rule said "kaise ho
is BAD, lead with a specific concrete reference". That rule was the bug.

The user doesn't want a forensic robot opening with "अरे, बेटी की तबियत कैसी
अब?" out of nowhere — she wants a sister who first checks in warmly, THEN
mentions what she's been thinking about.

Open the voice note with a real, respectfully-phrased check-in:
  - "Manimala ji, namaste! आज का दिन कैसा रहा?"
  - "शाम हो गयी Sonal ji — आज का दिन कैसा रहा?"
  - "Hi दीदी! आज याद आयी आपकी।"

Then ease into the substance. The transition word matters:
  - "वैसे, …"
  - "एक बात बताऊँ?"
  - "अरे हाँ — कल मैं सोच रही थी आपके business के बारे में …"

═══════════════════════════════════════════════════════════════════════════
RULE 3 — LENGTH: 30-60 SECONDS OF VOICE NOTE.
═══════════════════════════════════════════════════════════════════════════

The old prompt capped at 3-8 seconds. Too short for warmth. The new target
is 30-60 seconds spoken — roughly 80-200 chars in Hindi/Devanagari depending
on script. Don't pad; if substance is genuinely short, lean longer on warmth
opener, then substance, then a soft close ("बताइएगा क्या लगा" / "जब time
मिले, बताना" / "रुक के सुनना, कोई जल्दी नहीं").

═══════════════════════════════════════════════════════════════════════════
RULE 4 — ANTI-RELENTLESS. DON'T REPEAT YESTERDAY.
═══════════════════════════════════════════════════════════════════════════

You will be given a section "=== Recently Sent Nudges ===" in the user
message — a list of the user's recent nudges from the past 14 days. SCAN
THIS FIRST.

  - DO NOT touch the same topic as ANY nudge in that list, UNLESS the user
    re-raised it in their reactive conversation since.
  - DO NOT use the same opener as the last 2-3 nudges (vary "namaste" /
    "Hi didi" / "shaam ho gayi" / "subah ka waqt hai").
  - If you keep landing on the same emotionally-salient fact (the daughter's
    foot, a recent worry), STOP and pick something else from the dossier
    that hasn't been touched.

  Better to talk about a small everyday thing she shared once (an interest,
  a recipe, her saree business, her preferred chai) than to repeatedly probe
  the same hard topic.

═══════════════════════════════════════════════════════════════════════════
RULE 5 — VOICE-NOTE MEDIUM. NO MARKDOWN. NO EMOJIS.
═══════════════════════════════════════════════════════════════════════════

Plain spoken sentences only. Sarvam TTS reads literally — anything formatted
gets spoken as garbled punctuation, and **emojis get spoken as their unicode
names ("face with tears of joy")** which is unusable in a voice note.

  ❌ Forbidden in output: 😀 😄 😊 ❤️ 👍 🙏 and any other emoji codepoint.
  ❌ Forbidden: markdown asterisks, bullets, hashes, quoted blocks.

If you feel the impulse to add an emoji, use a word that carries the same
warmth ("हँसी आ गयी", "दिल खुश हुआ", "shukriya").

═══════════════════════════════════════════════════════════════════════════
RULE 6 — TWO CASES BASED ON MEMORY STATE
═══════════════════════════════════════════════════════════════════════════

**Case A — Returning user with memory/recent conversation history:**

After the warm opener, weave in ONE concrete reference from what you remember
or from recent conversation. Vary which fact across nudges (per Rule 4).

  Example, Manimala morning:
  "Manimala ji, namaste! Aaj ka din kaisa shuru ho raha hai? Vaise, kal
  aapne Surat trip ki baat ki thi — Diwali ke liye plan ho raha hai na?
  Jab time mile, sunna chahungi kaisa chal raha hai planning."

**Case B — New user, empty memory:**

Clean time-of-day greeting. No invented context, no fake familiarity. Aap-form.

  ✅ "Namaste! Subah ka waqt hai — aaj ki shuruwat kaisi hai? Jab time mile,
     baat karte hain. Main hoon idhar."

═══════════════════════════════════════════════════════════════════════════
HARD CONSTRAINTS (both cases)
═══════════════════════════════════════════════════════════════════════════

- Open with WARMTH (namaste / kaisa raha / aaj ka din kaisa) BEFORE substance.
- Aap-form throughout. NEVER kaisi ho / kar rahi ho / bata.
- 80-200 chars Hindi/Devanagari (≈ 30-60s spoken). Adjust for other scripts.
- NEVER make up details. NEVER pretend to remember something you don't.
- No "मैंने आपके लिए" / "मैंने सोचा कि" repeated openers — vary.
- No emojis. No markdown. No asterisks. No bullets.
- Don't apologise for messaging. Don't ask permission to talk.
- Ask AT MOST one short question.
- Match the user's number language (Hindi word if they use Hindi, English
  digits if English).

The nudge message is the "out" field of your JSON response (see the output
format below). Do any planning silently in "cot"; "out" is just the check-in
the user hears — nothing else.
"""


def build_nudge_prompts(
    llm: BaseLLM,
    *,
    domain: str,
    slot: str,
    user_profile: str,
    memory_summary: str,
    extracted_facts: str,
    recent_messages: List[Dict[str, str]],
    recent_nudge_texts: Optional[List[str]] = None,
) -> tuple:
    """Build (system_prompt, user_message) for a nudge LLM call.

    Returns the same (system, user) shape that BaseLLM._call_api accepts.

    `recent_nudge_texts` is the last 14 days of nudges already sent to this
    user. When provided, they're injected into the user message as a
    "do NOT repeat these topics" list so the model can apply Rule 4 of
    NUDGE_INSTRUCTION (anti-relentless).
    """
    system_prompt = (
        llm._build_system_prompt(domain, user_profile, memory_summary, extracted_facts)
        + "\n\n"
        + NUDGE_INSTRUCTION
        + _JSON_OUTPUT_INSTRUCTION
    )

    parts = []
    if recent_messages:
        parts.append("=== Recent Conversation (for context — pick up from here) ===")
        for msg in recent_messages:
            role_label = "User" if msg["role"] == "user" else "भाई (you)"
            parts.append(f"{role_label}: {msg['content']}")
        parts.append("=== End Recent Conversation ===\n")
    else:
        parts.append("(No prior conversation — keep it a casual hello.)\n")

    if recent_nudge_texts:
        parts.append("=== Recently Sent Nudges (do NOT repeat these topics) ===")
        for i, text in enumerate(recent_nudge_texts, 1):
            parts.append(f"[{i}] {text}")
        parts.append("=== End Recently Sent Nudges ===\n")

    parts.append(f"Time slot: {_slot_time_hint(slot)}.\n" "Generate the nudge now.")
    return system_prompt, "\n".join(parts)


def generate_nudge_text(
    llm: BaseLLM,
    *,
    slot: str,
    user_profile: str,
    memory_summary: str,
    extracted_facts: str,
    recent_messages: List[Dict[str, str]],
    recent_nudge_texts: Optional[List[str]] = None,
    domain: str = "hr_admin",
) -> Optional[str]:
    """Generate the nudge text via the LLM.

    Runs through the same cot/out JSON contract as normal replies, so reasoning
    can never leak into the spoken nudge. Returns the parsed "out" (cot is
    logged server-side, never delivered), or ``None`` if the JSON could not be
    parsed even after retries — the caller should then SKIP this nudge rather
    than speak the canned fallback as an unprompted "say it again?" message.
    """
    system_prompt, user_message = build_nudge_prompts(
        llm,
        domain=domain,
        slot=slot,
        user_profile=user_profile,
        memory_summary=memory_summary,
        extracted_facts=extracted_facts,
        recent_messages=recent_messages,
        recent_nudge_texts=recent_nudge_texts,
    )
    result = llm._generate_structured(system_prompt, user_message)
    if not result.get("parsed", True):
        logger.warning("Nudge cot/out parse failed; skipping nudge (no fallback send).")
        return None
    return result["text"]


# ── Scheduler loop ────────────────────────────────────────────────────


async def nudge_loop(
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str, Optional[str], Optional[Path]], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """Forever-loop that fires nudges for opted-in users at the configured slots.

    Args:
        config: app config (reads nudge_* fields)
        store: conversation store (for memory/history/last-nudge lookups)
        send_fn: blocking callable `(chat_id, slot, text) -> None` that
            actually delivers the nudge as a voice message.
        phone_hash_fn: maps a `tg_<chat_id>` phone string to its 12-char hash.
    """
    interval = max(60, config.nudge_check_interval_seconds)
    if is_wildcard_allowlist(config.nudge_phones):
        allowlist_desc = "all-active-users"
    else:
        allowlist_desc = str(len(parse_allowlist(config.nudge_phones)))
    logger.info(
        "Nudge loop starting (enabled=%s, interval=%ds, allowlist=%s)",
        config.nudge_enabled,
        interval,
        allowlist_desc,
    )

    loop = asyncio.get_running_loop()
    while True:
        try:
            if config.nudge_enabled:
                # LLM + TTS + send are blocking HTTP calls — run in a thread so
                # the event loop stays responsive to webhook requests.
                await loop.run_in_executor(
                    None,
                    _run_one_nudge_pass,
                    config,
                    store,
                    send_fn,
                    phone_hash_fn,
                )
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.exception("Nudge loop pass failed: %s", e)
        await asyncio.sleep(interval)


def _run_one_nudge_pass(
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str, Optional[str], Optional[Path]], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """One scan of all opted-in users — sends nudges to whoever is due."""
    now_ist = datetime.now(IST)
    slot = current_slot(
        now_ist,
        morning_hour=config.nudge_morning_hour_ist,
        night_hour=config.nudge_night_hour_ist,
        window_minutes=config.nudge_window_minutes,
        afternoon_hour=config.nudge_afternoon_hour_ist,
    )
    if slot is None:
        return  # not in a firing window

    active_phones = store.list_recently_active_phones(
        days=config.nudge_active_user_days
    )

    candidates = select_nudge_candidates(
        active_phones, config.nudge_phones, phone_hash_fn
    )
    if not candidates:
        return

    logger.info("Nudge pass: slot=%s candidates=%d", slot, len(candidates))

    for phone in candidates:
        try:
            _maybe_nudge_one(
                phone=phone,
                slot=slot,
                now_ist=now_ist,
                config=config,
                store=store,
                send_fn=send_fn,
                phone_hash_fn=phone_hash_fn,
            )
        except Exception as e:
            logger.error(
                "Nudge failed for user=%s: %s",
                phone_hash_fn(phone),
                e,
            )


def _generate_nudge_v2(
    *, phone: str, slot: str, store: ConversationStore, config: Config
) -> Optional[Any]:
    """Generate a nudge via the v2 ProactiveThinker (brainstorm → critique →
    draft → judge, with tools + the text-artifact channel). Morning/night use
    the substantive loop. Returns the NudgeCandidate, or None on error so the
    caller skips the slot rather than sending garbage."""
    from src.bhai.proactive.agent_input import build_agent_input
    from src.bhai.proactive.thinker import (
        ProactiveThinker,
        ToolRunner,
        _make_anthropic_caller,
    )

    try:
        agent_input = build_agent_input(store, phone, recent_turns=20)
        thinker = ProactiveThinker(
            config,
            anthropic_caller=_make_anthropic_caller(config.anthropic_api_key),
            tool_runner=ToolRunner(
                config=config,
                artifacts_base_dir=DATA_DIR / "proactive",
                audit_base_dir=DATA_DIR / "proactive",
                kb_dir=KNOWLEDGE_BASE_DIR,
                tts=None,
            ),
            model=getattr(config, "anthropic_model", None) or "claude-sonnet-4-6",
        )
        # Afternoon = the substantive utility work (bhAI hard at work for her
        # while she's at work). Morning/night = light, grounded check-ins (the
        # relational bookends; a night check-in may fold in an organic joke).
        if slot == SLOT_AFTERNOON:
            return thinker.think_substantive(agent_input, slot)
        return thinker.think_checkin(agent_input, slot)
    except Exception as e:
        logger.exception("v2 nudge generation failed for %s: %s", phone, e)
        return None


def _maybe_nudge_one(
    *,
    phone: str,
    slot: str,
    now_ist: datetime,
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str, Optional[str], Optional[Path]], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """Decide and (if eligible) send a nudge to one user."""
    phone_id = phone_hash_fn(phone)

    last_msg_time = store._get_last_message_time(phone)
    last_nudge_time = store.get_last_nudge_sent(phone, slot)
    throttle_hours = store.get_throttle_hours(phone)
    last_any_nudge_time = (
        store.get_last_any_nudge_sent(phone) if throttle_hours else None
    )

    if not should_nudge_user(
        now_ist=now_ist,
        slot=slot,
        last_user_message_at=last_msg_time,
        last_nudge_at=last_nudge_time,
        throttle_hours=throttle_hours,
        last_any_nudge_at=last_any_nudge_time,
    ):
        return

    if not phone.startswith("tg_"):
        logger.warning("Skipping non-Telegram phone for nudge: user=%s", phone_id)
        return
    try:
        chat_id = int(phone[len("tg_") :])
    except ValueError:
        logger.warning("Bad chat_id for nudge: user=%s", phone_id)
        return

    cand = _generate_nudge_v2(phone=phone, slot=slot, store=store, config=config)
    if not cand or not cand.text:
        logger.warning("Empty nudge generated for user=%s — skipping", phone_id)
        return

    logger.info(
        "Sending nudge to user=%s slot=%s cat=%s len=%d",
        phone_id,
        slot,
        cand.category,
        len(cand.text),
    )
    # Voice note + (if the draft produced one) a paste-able text artifact as a
    # separate message. record_nudge_outcome logs the content to nudge_log +
    # flips the grounded thread dormant→active so the feedback loop sees it.
    send_fn(chat_id, slot, cand.text, cand.text_artifact, cand.artifact_path)
    store.record_nudge_outcome(
        phone, slot, cand.thread_slug, category=cand.category, text=cand.text
    )


def build_and_generate_nudge(
    *,
    phone: str,
    slot: str,
    store: ConversationStore,
    config: Config,
) -> Optional[str]:
    """Pull the user's context from the store and run the LLM.

    Returns the nudge text, or ``None`` when generation failed to produce a
    valid cot/out reply — the caller skips sending in that case.
    """
    llm = create_llm(config)
    user_profile = llm.load_user_profile(phone)

    memory = store.get_memory(phone)
    memory_summary = ""
    extracted_facts_str = ""
    if memory:
        memory_summary = memory["summary"]
        if memory["facts"]:
            extracted_facts_str = "\n".join(f"- {f}" for f in memory["facts"])

    recent = store.get_recent_messages(phone, limit=10)
    recent_nudge_texts = store.list_recent_nudge_texts(phone, days=14)
    return generate_nudge_text(
        llm,
        slot=slot,
        user_profile=user_profile,
        memory_summary=memory_summary,
        extracted_facts=extracted_facts_str,
        recent_messages=recent,
        recent_nudge_texts=recent_nudge_texts,
    )
