"""
Proactive nudges (option B): twice-daily context-aware check-ins.

bhAI initiates a short voice message in the morning (~10am IST) and at
night (~9pm IST) for opted-in pilot users. The nudge is generated by the
same LLM with the user's full context (memory, profile, recent history)
plus a "nudge mode" instruction so it picks up where the last conversation
left off rather than launching into a sales pitch.

Safety rails:
- NUDGE_ENABLED master kill switch (default false)
- NUDGE_PHONES allow-list of phone hashes (empty = nobody gets nudged)
- One nudge per slot per day (tracked in `nudges` table)
- Quiet hours: never fire between 23:00 and 08:00 IST
- Skip if user just messaged (active conversation, don't interrupt)
- Skip if user has fewer than 1 message in the last `nudge_active_user_days`
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, time as dtime, timedelta, timezone
from typing import Any, Callable, Dict, List, Optional

from src.bhai.config import Config
from src.bhai.llm import create_llm
from src.bhai.llm.base import BaseLLM
from src.bhai.memory.store import ConversationStore

logger = logging.getLogger("bhai.nudges")

IST = timezone(timedelta(hours=5, minutes=30))

# Slots — extend here if we add more nudge times later
SLOT_MORNING = "morning"
SLOT_NIGHT = "night"

# Quiet hours: never nudge before this hour or after this hour, IST.
QUIET_BEFORE_HOUR = 8
QUIET_AFTER_HOUR = 23

# Don't nudge if the user has messaged in the last N hours — they're active,
# we don't need to interrupt with a check-in.
SKIP_IF_USER_ACTIVE_HOURS = 2

# One nudge per slot per 18 hours (prevents double-fire if loop overlaps a window
# or the process restarts mid-window).
MIN_GAP_BETWEEN_SAME_SLOT_HOURS = 18


# ── Pure decision logic (testable without DB / network) ───────────────


def current_slot(
    now_ist: datetime,
    morning_hour: int,
    night_hour: int,
    window_minutes: int,
) -> Optional[str]:
    """If `now_ist` falls inside a slot's firing window, return the slot name.

    Each slot has a window of `window_minutes` starting at the configured hour
    (e.g. morning_hour=10, window=30 → fires between 10:00 and 10:30 IST).
    Outside any window, returns None.
    """
    if not (QUIET_BEFORE_HOUR <= now_ist.hour < QUIET_AFTER_HOUR):
        return None

    slot_starts = {
        SLOT_MORNING: dtime(hour=morning_hour),
        SLOT_NIGHT: dtime(hour=night_hour),
    }
    now_t = now_ist.time()
    for slot, start in slot_starts.items():
        end_dt = (
            datetime.combine(now_ist.date(), start) + timedelta(minutes=window_minutes)
        ).time()
        if start <= now_t <= end_dt:
            return slot
    return None


def should_nudge_user(
    *,
    now_ist: datetime,
    slot: str,
    last_user_message_at: Optional[datetime],
    last_nudge_at: Optional[datetime],
) -> bool:
    """Pure check: should we send a `slot` nudge to this user right now?

    - Skip if they messaged us in the last SKIP_IF_USER_ACTIVE_HOURS — don't
      interrupt an active conversation.
    - Skip if we've already nudged this slot in the last
      MIN_GAP_BETWEEN_SAME_SLOT_HOURS — once a window per day.
    """
    if last_user_message_at is not None:
        if now_ist - last_user_message_at < timedelta(hours=SKIP_IF_USER_ACTIVE_HOURS):
            return False

    if last_nudge_at is not None:
        if now_ist - last_nudge_at < timedelta(hours=MIN_GAP_BETWEEN_SAME_SLOT_HOURS):
            return False

    # Slot name must be one we know about.
    return slot in (SLOT_MORNING, SLOT_NIGHT)


def parse_allowlist(raw: str) -> List[str]:
    """Comma/whitespace-separated phone-hash allowlist → cleaned list."""
    if not raw:
        return []
    return [p.strip() for p in raw.replace("\n", ",").split(",") if p.strip()]


# ── Prompt construction ──────────────────────────────────────────────


def _slot_time_hint(slot: str) -> str:
    """Human-readable time-of-day hint passed to the LLM."""
    if slot == SLOT_MORNING:
        return "सुबह (around 10am IST)"
    if slot == SLOT_NIGHT:
        return "रात (around 9pm IST)"
    return slot


NUDGE_INSTRUCTION = """\
=== Nudge Mode ===
You are starting a NEW message to the user — they did NOT message you. You're
reaching out first, like a sister who suddenly thought of them.

This is a CHECK-IN, not a request, not a survey, not a reminder. The whole point
is to feel like a friend who remembers. If you make this feel transactional, you
have failed.

Hard rules:
- 1-2 sentences MAX. Under 200 Devanagari characters. The voice note should be
  3-8 seconds, not 15.
- Pick up something CONCRETE from your last conversation if there's anything
  worth picking up — a person they mentioned (बेटा/बेटी/पति/माँ), a worry, a
  plan, a feeling. "अरे, बेटी की तबियत कैसी अब?" beats "कैसे हो?".
- If memory is empty / nothing concrete to reference: just a casual time-of-day
  hello. NEVER make up details. NEVER pretend to remember something you don't.
- Don't be needy. Don't say "मैं सोच रही थी आपके बारे में" or
  "बहुत दिन हो गए". No guilt-trips.
- Don't apologize for messaging. Don't ask permission to talk.
- Ask AT MOST one short question. Often zero questions is right — just a warm
  observation, leaving space for them to reply if they want.
- No markdown. No asterisks. No bullets. Plain Devanagari sentences only.
- Match the user's number language if you mention numbers (Hindi word if they
  use Hindi, English digits if they use English).
- No "ESCALATE:" line, no "EMOTIONS_JSON:" line — just the plain text.

Output ONLY the nudge text. Nothing else.
"""


def build_nudge_prompts(
    llm: BaseLLM,
    *,
    domain: str,
    slot: str,
    user_profile: str,
    memory_summary: str,
    extracted_facts: str,
    recent_messages: List[Dict[str, str]],
) -> tuple:
    """Build (system_prompt, user_message) for a nudge LLM call.

    Returns the same (system, user) shape that BaseLLM._call_api accepts.
    """
    system_prompt = (
        llm._build_system_prompt(domain, user_profile, memory_summary, extracted_facts)
        + "\n\n"
        + NUDGE_INSTRUCTION
    )

    parts = []
    if recent_messages:
        parts.append("=== Recent Conversation (for context — pick up from here) ===")
        for msg in recent_messages:
            role_label = "User" if msg["role"] == "user" else "भाई (you)"
            parts.append(f"{role_label}: {msg['content']}")
        parts.append("=== End Recent Conversation ===\n")
    else:
        parts.append("(No prior conversation — keep it a casual hello.)\n")

    parts.append(
        f"Time slot: {_slot_time_hint(slot)}.\n"
        "Generate the nudge now."
    )
    return system_prompt, "\n".join(parts)


def generate_nudge_text(
    llm: BaseLLM,
    *,
    slot: str,
    user_profile: str,
    memory_summary: str,
    extracted_facts: str,
    recent_messages: List[Dict[str, str]],
    domain: str = "hr_admin",
) -> str:
    """Generate the nudge text via the LLM. Returns cleaned plain text."""
    system_prompt, user_message = build_nudge_prompts(
        llm,
        domain=domain,
        slot=slot,
        user_profile=user_profile,
        memory_summary=memory_summary,
        extracted_facts=extracted_facts,
        recent_messages=recent_messages,
    )
    raw = llm._call_api_with_retry(system_prompt, user_message)
    return BaseLLM._clean_response(raw)


# ── Scheduler loop ────────────────────────────────────────────────────


async def nudge_loop(
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """Forever-loop that fires nudges for opted-in users at the configured slots.

    Args:
        config: app config (reads nudge_* fields)
        store: conversation store (for memory/history/last-nudge lookups)
        send_fn: blocking callable `(chat_id, slot, text) -> None` that
            actually delivers the nudge as a voice message.
        phone_hash_fn: maps a `tg_<chat_id>` phone string to its 12-char hash.
    """
    interval = max(60, config.nudge_check_interval_seconds)
    logger.info(
        "Nudge loop starting (enabled=%s, interval=%ds, allowlist_size=%d)",
        config.nudge_enabled,
        interval,
        len(parse_allowlist(config.nudge_phones)),
    )

    loop = asyncio.get_running_loop()
    while True:
        try:
            if config.nudge_enabled:
                # LLM + TTS + send are blocking HTTP calls — run in a thread so
                # the event loop stays responsive to webhook requests.
                await loop.run_in_executor(
                    None,
                    _run_one_nudge_pass,
                    config,
                    store,
                    send_fn,
                    phone_hash_fn,
                )
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.exception("Nudge loop pass failed: %s", e)
        await asyncio.sleep(interval)


def _run_one_nudge_pass(
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """One scan of all opted-in users — sends nudges to whoever is due."""
    now_ist = datetime.now(IST)
    slot = current_slot(
        now_ist,
        morning_hour=config.nudge_morning_hour_ist,
        night_hour=config.nudge_night_hour_ist,
        window_minutes=config.nudge_window_minutes,
    )
    if slot is None:
        return  # not in a firing window

    allowlist = set(parse_allowlist(config.nudge_phones))
    if not allowlist:
        return  # no one opted in

    active_phones = store.list_recently_active_phones(
        days=config.nudge_active_user_days
    )

    candidates = [p for p in active_phones if phone_hash_fn(p) in allowlist]
    if not candidates:
        return

    logger.info(
        "Nudge pass: slot=%s candidates=%d", slot, len(candidates)
    )

    for phone in candidates:
        try:
            _maybe_nudge_one(
                phone=phone,
                slot=slot,
                now_ist=now_ist,
                config=config,
                store=store,
                send_fn=send_fn,
                phone_hash_fn=phone_hash_fn,
            )
        except Exception as e:
            logger.error(
                "Nudge failed for user=%s: %s",
                phone_hash_fn(phone),
                e,
            )


def _maybe_nudge_one(
    *,
    phone: str,
    slot: str,
    now_ist: datetime,
    config: Config,
    store: ConversationStore,
    send_fn: Callable[[int, str, str], None],
    phone_hash_fn: Callable[[str], str],
) -> None:
    """Decide and (if eligible) send a nudge to one user."""
    phone_id = phone_hash_fn(phone)

    last_msg_time = store._get_last_message_time(phone)
    last_nudge_time = store.get_last_nudge_sent(phone, slot)

    if not should_nudge_user(
        now_ist=now_ist,
        slot=slot,
        last_user_message_at=last_msg_time,
        last_nudge_at=last_nudge_time,
    ):
        return

    if not phone.startswith("tg_"):
        logger.warning("Skipping non-Telegram phone for nudge: user=%s", phone_id)
        return
    try:
        chat_id = int(phone[len("tg_") :])
    except ValueError:
        logger.warning("Bad chat_id for nudge: user=%s", phone_id)
        return

    text = build_and_generate_nudge(
        phone=phone, slot=slot, store=store, config=config
    )
    if not text:
        logger.warning("Empty nudge generated for user=%s — skipping", phone_id)
        return

    logger.info(
        "Sending nudge to user=%s slot=%s len=%d", phone_id, slot, len(text)
    )
    send_fn(chat_id, slot, text)
    store.record_nudge_sent(phone, slot)


def build_and_generate_nudge(
    *,
    phone: str,
    slot: str,
    store: ConversationStore,
    config: Config,
) -> str:
    """Pull the user's context from the store and run the LLM. Returns cleaned text."""
    llm = create_llm(config)
    user_profile = llm.load_user_profile(phone)

    memory = store.get_memory(phone)
    memory_summary = ""
    extracted_facts_str = ""
    if memory:
        memory_summary = memory["summary"]
        if memory["facts"]:
            extracted_facts_str = "\n".join(f"- {f}" for f in memory["facts"])

    recent = store.get_recent_messages(phone, limit=10)
    return generate_nudge_text(
        llm,
        slot=slot,
        user_profile=user_profile,
        memory_summary=memory_summary,
        extracted_facts=extracted_facts_str,
        recent_messages=recent,
    )
